version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "20:00"
      timezone: "Europe/Lisbon"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "20:00"
      timezone: "Europe/Lisbon"
    open-pull-requests-limit: 5

